### ISSUE TITLE
Cannot resolve com.oracle:ojdbc14:10.2.0.4.0

### ISSUE THREAD

**Issue by adaivskenan** [SkyAPM/java-plugin-extensions#27]
Load this maven project, I got one error: Could not find artifact com.oracle:ojdbc14:jar:10.2.0.4.0 in central.
I checked the maven repository. This address "https://repo1.maven.org/maven2/com/oracle/ojdbc14/10.2.0.4.0/" only has pom files
. So, The type of 'com.oracle:ojdbc14:10.2.0.4.0''s dependency should be pom.
```xml
       <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc14</artifactId>
            <version>${ojdbc14.version}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
```

**Comment by wu-sheng** [comment]
Check this, https://github.com/SkyAPM/java-plugin-extensions/blob/master/.github/workflows/ci.yaml#L19

**Comment by adaivskenan** [comment]
Thanks!
