### ISSUE TITLE
Support for Spring application.yml?

### ISSUE THREAD

**Issue by xunyao4dev** [SkyAPM/java-plugin-extensions#35]
I don't want to set the `service_name` by `java -javaagent:/path/to/skywalking-agent.jar -Dskywalking.agent.service_name=myapp -jar your-application.jar` or `export SW_SERVICE_NAME myapp`, Is there any way to read property `spring.application.name` in the springboot config file `application.yml` automaticlly?

**Comment by wu-sheng** [comment]
I think this has been provided by the skywalking agent kernel.
